---
# ==================================================================================================
#
# Copyright Bloody Mage <gd.github@bloodymage.org>
#
# MIT License
# SPDX-License-Identifier: MIT
#
# ==================================================================================================
namespace: bloodymage
name: autonomy
version: 0.11.0
readme: "README.md"
authors:
  - G Derber <gd.github@bloodymage.org>
description: Installs your own self-hosted network services.
license_file: "LICENSE.md"
tags:
  - selfhosted
  - autonomy
  - bloodymage
  - dns
  - activedirectory
  - email
  - dovecot
  - postfix
dependencies:
  - community.crypto
  - community.network
repository: https://github.com/bloodymage/ansible-collection-autonomy
documentation: http://docs.bloodymage.org
homepage: https://bloodymage.org
issues: https://github.com/bloodymage/ansible-collection-autonomy/issues
build_ignore:
  - .gitignore
  - *.tar.gz
