---
- name: "Copy CA Certificates Samba File Server."
  ansible.builtin.copy:
    src: "{{ ownca_ca_directory }}/certs/{{ autonomy_org_name }}-{{ item.name }}-ca_{{ autonomy_ownca_privatekey_type | lower }}.crt"
    dest: "/srv/samba/pki/{{ autonomy_org_name }}-{{ item.name }}-ca_{{ autonomy_ownca_privatekey_type | lower }}.crt"
    owner: root
    group: root
    mode: "0660"
  loop: "{{ autonomy_ownca_certificate_authorities }}"
  become: yes
  when:
    - inventory_hostname == groups['samba_file_servers'][0] | default([])

- name: "Copy CA Certificate Chains Samba File Server."
  ansible.builtin.copy:
    src: "{{ ownca_ca_directory }}/certs/{{ autonomy_org_name }}-{{ item.name }}-ca-chain_{{ autonomy_ownca_privatekey_type | lower }}.crt"
    dest: "/srv/samba/pki/{{ autonomy_org_name }}-{{ item.name }}-ca-chain_{{ autonomy_ownca_privatekey_type | lower }}.crt"
    owner: root
    group: root
    mode: "0660"
  loop: "{{ autonomy_ownca_certificate_authorities }}"
  become: yes
  when:
    - inventory_hostname == groups['samba_file_servers'][0] | default([])
    - item.name != "root"

- name: "Copy CA Certificates Samba File Server."
  ansible.builtin.copy:
    src: "{{ ownca_ca_directory }}/certs/{{ autonomy_org_name }}-{{ item.name }}-ca_{{ autonomy_ownca_privatekey_type | lower }}.der"
    dest: "/srv/samba/pki/{{ autonomy_org_name }}-{{ item.name }}-ca_{{ autonomy_ownca_privatekey_type | lower }}.cer"
    owner: root
    group: root
    mode: "0660"
  loop: "{{ autonomy_ownca_certificate_authorities }}"
  become: yes
  when:
    - inventory_hostname == groups['samba_file_servers'][0] | default([])

- name: "Copy CA Certificate Chains Samba File Server."
  ansible.builtin.copy:
    src: "{{ ownca_ca_directory }}/certs/{{ autonomy_org_name }}-{{ item.name }}-ca-chain_{{ autonomy_ownca_privatekey_type | lower }}.der"
    dest: "/srv/samba/pki/{{ autonomy_org_name }}-{{ item.name }}-ca-chain_{{ autonomy_ownca_privatekey_type | lower }}.cer"
    owner: root
    group: root
    mode: "0660"
  loop: "{{ autonomy_ownca_certificate_authorities }}"
  become: yes
  when:
    - inventory_hostname == groups['samba_file_servers'][0] | default([])
    - item.name != "root"
