---
- name: Install Apache site.conf
  ansible.builtin.template:
    src: "etc/apache2/sites-available/ apache-site.conf.j2"
    dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ virtual_hosts }}"
  become: yes
  when:
    - virtual_hosts is defined
    - item.content is defined
    - item.content == "crls"
    - item.enabled is defined
    - item.enabled
  notify: reload apache
  tags:
    - ownca-crl-distribution-points
    - ownca_crl_distribution_points

- name: Copy CRLs to server.
  include_tasks: "install_crls.yml"
  loop: "{{ virtual_hosts }}"
  loop_control:
    loop_var: vhost
  when:
    - virtual_hosts is defined
    - vhost.content is defined
    - vhost.content == "crls"
    - vhost.enabled is defined
    - vhost.enabled
  tags:
    - ownca-crl-distribution-points
    - ownca_crl_distribution_points
