---
# ==================================================================================================
#
# Convert these certificate from PEM to DER format.
#
# This is done because Windows frequently needs DER format.
#
# Currently split into two tasks.  The 'root' ca does not have a chain file.  Need a way to make
# this idempotent.
#
# ==================================================================================================
- name: "Convert CA Certificates to DER format."
  community.crypto.x509_certificate_convert:
    src_path: "{{ autonomy_ownca_ca_certs_directory }}/{{ autonomy_org_name }}-{{ item.name }}-ca.crt"
    dest_path: "{{ autonomy_ownca_ca_certs_directory }}/{{ autonomy_org_name }}-{{ item.name }}-ca.der"
    format: "der"
  become: no
  loop: "{{ autonomy_ownca_certificate_authorities }}"
  delegate_to: localhost
  run_once: yes
  tags:
    - ownca
    - ownca-root
    - ownca-intermediate
    - ownca-issuing

- name: "Convert CA Certificates to DER format."
  community.crypto.x509_certifacate_convert:
    src_path: "{{ autonomy_ownca_ca_certs_directory }}/{{ autonomy_org_name }}-{{ item.name }}-ca-chain.crt"
    dest_path: "{{ autonomy_ownca_ca_certs_directory }}/{{ autonomy_org_name }}-{{ item.name }}-ca-chain.der"
    format: "der"
  become: no
  loop: "{{ autonomy_ownca_certificate_authorities }}"
  delegate_to: localhost
  run_once: yes
  when:
    - item.name != "root"
  tags:
    - ownca
    - ownca-root
    - ownca-intermediate
    - ownca-issuing
