---
# ==================================================================================================
#
# Creates dh params for individual hosts.
#
# This takes forever on a RPi.  What are the security implications for generating elsewhere and
# transferring to the RPi server later?
#
# This currently only works if the privatekey type is 'DSA' or 'RSA'.  While it is possible to
# use Diffie-Hellman parameters for Elliptical Curve Private keys, it is currently not possible
# using the ansible modules.
#
# ==================================================================================================
- name: "Generate Diffie-Hellman Parameters."
  community.crypto.openssl_dhparam:
    path: "/etc/ssl/dhparams/{{ autonomy_fqdn }}.pem"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
    force: "{{ __host_dhparams_force_regeneration }}"
  become: true
  notify:
    - restart tls
  when:
    - autonomy_ownca_host_privatekey_type in ['DSA','RSA']
    - ansible_connection != "local"
  tags:
    - ownca
    - ownca-dhparams
    - ownca-host-dhparams
