---
# ==================================================================================================
#
#
#
# ==================================================================================================
- name: "Add intermediate Certificate Authorities."
  ansible.builtin.set_fact:
    autonomy_ownca_certificate_authorities: "{{ autonomy_ownca_certificate_authorities + [__certificate_authority] }}"
  loop: "{{ autonomy_zones }}"
  vars:
    __privatekey_file: "{{ autonomy_org_name }}-{{ item['name'] }}-ca.key"
    __certificate_authority:
      name: "{{ item['name'] }}"
      common_name: "{{ autonomy_org_name | title }} {{ item['name'] | title }} CA"
      ownca: "root"
      provider: "ownca"
      ca_id: "intermediate"
      zone_name: "{{ item['name'] }}."
      keyusage:
        - keyCertSign
        - cRLSign
      keyusage_critical: true
      basic_constraints:
        - 'CA:TRUE'
      privatekey_type: "{{ autonomy_ownca_intermediate_ca_privatekey_type }}"
      privatekey_size: "{{ autonomy_ownca_privatekey_size }}"
      privatekey_path: "{{ autonomy_ownca_ca_privatekey_directory }}/{{ __privatekey_file }}"
      org_unit_name: "{{ item['name'] }}"
      domain: "{{ item['domain'] }}"
      regenerate_privatekey: "{{ __ownca_intermediateca_privatekey_force_regeneration }}"
      regenerate_csr: "{{ __ownca_intermediateca_csr_force_regeneration }}"
      regenerate_cert: "{{ __ownca_intermediateca_cert_force_regeneration }}"
  when:
    - item.type != "public"
    - item.type != "overlay"
  tags:
    - ownca
    - ownca-root
    - ownca-intermediate
    - ownca-issuing

- name: "Add issuing Certificate Authorities."
  ansible.builtin.set_fact:
    autonomy_ownca_certificate_authorities: "{{ autonomy_ownca_certificate_authorities + [__certificate_authority] }}"
  loop: "{{ autonomy_zones | product(autonomy_ownca_issuing_authorities) }}"
  vars:
    __name: "{{ item[0]['name'] | title }} {{ item[1] | title}}"
    __name_alt: "{{ item[0]['name'] }}-{{ item[1] }}"
    __privatekey_file: "{{ autonomy_org_name }}-{{ __name_alt }}-ca.key"
    __certificate_authority:
      name: "{{ __name_alt }}"
      common_name: "{{ autonomy_org_name | title }} {{ __name }} CA"
      ownca: "intermediate"
      provider: "ownca"
      ca_id: "{{ item[1] }}"
      zone_name: "{{ item[0]['name'] }}."
      keyusage:
        - keyCertSign
        - cRLSign
      keyusage_critical: yes
      basic_constraints:
        - 'CA:TRUE'
      privatekey_type: "{{ autonomy_ownca_issuing_ca_privatekey_type }}"
      privatekey_size: "{{ autonomy_ownca_privatekey_size }}"
      privatekey_path: "{{ autonomy_ownca_ca_privatekey_directory }}/{{ __privatekey_file }}"
      org_unit_name: "{{ item[0]['name'] }}"
      domain: "{{ item[0]['domain'] }}"
      regenerate_privatekey: "{{ __ownca_intermediateca_privatekey_force_regeneration }}"
      regenerate_csr: "{{ __ownca_intermediateca_csr_force_regeneration }}"
      regenerate_cert: "{{ __ownca_intermediateca_cert_force_regeneration }}"
  when:
    - item[0].type != "public"
    - item[0].type != "overlay"
  tags:
    - ownca
    - ownca-root
    - ownca-intermediate
    - ownca-issuing

# ==================================================================================================
#
# Tasks: Create Directories
#
#
#
# ==================================================================================================
- name: "Create PKI Directory."
  ansible.builtin.file:
    path: '{{ autonomy_ownca_ca_directory }}/{{ item }}'
    state: directory
    owner: "{{ autonomy_user }}"
    group: "{{ autonomy_group }}"
    mode: '0700'
  loop:
    - private
    - certs
    - crl
    - csr
    - newcerts
    - db
  delegate_to: localhost
  run_once: true
  become: false
  tags:
    - ownca
    - ownca-root
    - ownca-intermediate
    - ownca-issuing

- name: "Create crl serial file."
  ansible.builtin.template:
    src: "serial.j2"
    dest: "{{ autonomy_ownca_ca_directory }}/db/{{ autonomy_org_name }}-{{ item.name }}-ca.crl.srl"
    owner: "{{ autonomy_user }}"
    group: "{{ autonomy_group }}"
    mode: "0600"
    force: false
  loop: "{{ autonomy_ownca_certificate_authorities }}"
  delegate_to: localhost
  become: false
  tags:
    - ownca
    - ownca-root
    - ownca-intermediate
    - ownca-issuing

- name: "Generate CA Private Key."
  community.crypto.openssl_privatekey:
    path: "{{ item['privatekey_path'] | default(__privatekey_path) }}"
    passphrase: "{{ lookup('community.general.passwordstore', __password_lookup) }}"
    type: "{{ __privatekey_type }}"
    size: "{{ item['privatekey_size'] }}"
    curve: "{{ __curve }}"
    cipher: "auto"
    owner: "{{ autonomy_user }}"
    group: "{{ autonomy_group }}"
    mode: "0400"
    backup: true
    force: "{{ item['regenerate_privatekey'] }}"
  loop: "{{ autonomy_ownca_certificate_authorities }}"
  delegate_to: localhost
  become: false
  vars:
    __privatekey_tmp_type: >-
      {% if item['privatekey_type'].lower() in ['ed25519','ed448'] %}
      {{ item['privatekey_type'] | capitalize }}
      {% else %}
      {{ item['privatekey_type'] | upper }}
      {% endif %}
    __privatekey_type: "{{ __privatekey_tmp_type | trim }}"
    __password_store_dir: "{{ autonomy_passdb }}/{{ item.domain }}/ownca"
    __password_store_id: "{{ __password_store_dir }}/ownca_{{ item.ca_id }}_password"
    __password_length: "length={{ autonomy_password_length }}"
    __password_overwrite: "overwrite={{ autonomy_overwrite_password }} backup=yes"
    __password_create: "create=true"
    __password_symbols: "nosymbols=true"
    __password_lookup: "{{ __password_store_id }} {{ __password_create }} {{ __password_length }} {{ __password_symbols }} {{ __password_overwrite }}"
    __password: "{{ lookup('community.general.passwordstore', __password_lookup) }}"
    __privatekey_file: "{{ autonomy_org_name }}-{{ item['name'] }}-ca.key"
    __privatekey_path: "{{ autonomy_ownca_ca_privatekey_directory }}/{{ __privatekey_file }}"
    __curve: "{{ autonomy_ownca_ecc_curve if __privatekey_type == 'ECC' else omit }}"
  tags:
    - ownca
    - ownca-root
    - ownca-intermediate
    - ownca-issuing
