---
# tasks file for sshca-user-certs
- name: "Ensure user has their .ssh directory"
  ansible.builtin.file:
    path: "/home/{{ autonomy_org_unit_name | upper }}/{{ item.username }}/.ssh"
    state: directory
    owner: "{{ item.id_number }}"
    group: "{{ item.id_number }}"
    mode: "0700"
  loop: "{{ __realm_users }}"
  become: yes
  when:
    - item.id_number is defined

- name: "Create user pki directories."
  ansible.builtin.file:
    path: "{{ autonomy_ownca_directory }}/users/{{ item.name }}"
    state: directory
    owner: "{{ autonomy_user }}"
    group: "{{ autonomy_group }}"
    mode: "{{ item.mode }}"
  become: no
  loop: "{{ sshca_user_pki_dirs }}"
  delegate_to: localhost
  run_once: yes

- name: "Create user certs."
  include_tasks: "sshca_user_certs_{{ item }}.yml"
  loop:
    - pkcs11

- name: "Create SSH Principals file for users."
  ansible.builtin.template:
    src: "ssh_principals.j2"
    dest: "/etc/ssh/auth_principals/{{ __realm }}{{ item.username }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ __realm_users }}"
  become: true
  vars:
    __realm: "{% if inventory_hostname not in groups['sssd'] %}{{ autonomy_org_unit_name | upper }}\\{% else %}{% endif %}"
  when:
    - item.id_number is defined
