---
- name: "Install packages."
  ansible.builtin.package:
    name: "{{ autonomy_unattended_upgrades_packages }}"
    state: present
  become: true

- name: "Install Configuration files."
  ansible.builtin.template:
    src: "{{ item.name }}.j2"
    dest: "{{ unattended_upgrades_config_dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0644') }}"
    validate: "{{ item.validate | default(none) }}"
    backup: true
  become: true
  loop: "{{ unattended_upgrades_config_files }}"
  notify: restart unattended-upgrades
