---
# tasks file for unattended_upgrades
# ======================================================================
#
# Tasks:
#
#
# ======================================================================
- name: "Include OS-specific variables."
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: no

- name: "Install and Configure Unattended Upgrades."
  include_tasks: "install.yml"
  when:
    - autonomy_unattended_upgrades_enabled

- name: "Remove Unattended Upgrades."
  include_tasks: "remove_{{ ansible_os_family | lower }}.yml"
  when:
    - autonomy_unattended_upgrades_enabled is falsy
