---
- name: "Install packages"
  ansible.builtin.package:
    name: "{{ autonomy_emacs_base_packages + autonomy_emacs_packages }}"
    state: present
  become: yes

- name: "Install Modified emacs.service file"
  ansible.builtin.template:
    src: service.j2
    dest: "/usr/lib/systemd/user/emacs.service"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: "daemon reload"

- name: "Enable emacs daemon service for all users and ensure it is not masked."
  ansible.builtin.systemd:
    name: emacs
    enabled: "{{ autonomy_emacs_daemon_enabled }}"
    force: false
    masked: false
    no_block: false
    scope: global
  become: true

# ==================================================================================================
#
#
#
# ==================================================================================================
- name: "Install Emacsclient.desktop"
  ansible.builtin.copy:
    src: "emacsclient.desktop"
    dest: "/usr/share/applications/emacsclient.desktop"
    owner: root
    group: root
    mode: "0644"
  become: yes
