---
# .gitconfig
autonomy_gitconfig_color_advice: ""
autonomy_gitconfig_color_advice_branch: ""
autonomy_gitconfig_color_blame_highlight_recent: ""
autonomy_gitconfig_color_blame_repeated_lines: ""
autonomy_gitconfig_color_branch: ""
autonomy_gitconfig_color_branch_current: ""
autonomy_gitconfig_color_branch_local: ""
autonomy_gitconfig_color_branch_plain: ""
autonomy_gitconfig_color_branch_remote: ""
autonomy_gitconfig_color_branch_upstream: ""
autonomy_gitconfig_color_diff: ""
autonomy_gitconfig_color_diff_commit: ""
autonomy_gitconfig_color_diff_context: ""
autonomy_gitconfig_color_diff_context_bold: ""
autonomy_gitconfig_color_diff_context_dimmed: ""
autonomy_gitconfig_color_diff_frag: ""
autonomy_gitconfig_color_diff_meta: ""
autonomy_gitconfig_color_diff_new: ""
autonomy_gitconfig_color_diff_new_bold: ""
autonomy_gitconfig_color_diff_new_dimmed: ""
autonomy_gitconfig_color_diff_new_moved: ""
autonomy_gitconfig_color_diff_new_moved_alternative: ""
autonomy_gitconfig_color_diff_new_moved_alternative_dimmed: ""
autonomy_gitconfig_color_diff_new_moved_dimmed: ""
autonomy_gitconfig_color_diff_old: ""
autonomy_gitconfig_color_diff_old_bold: ""
autonomy_gitconfig_color_diff_old_dimmed: ""
autonomy_gitconfig_color_diff_old_moved: ""
autonomy_gitconfig_color_diff_old_moved_alternative: ""
autonomy_gitconfig_color_diff_old_moved_alternative_dimmed: ""
autonomy_gitconfig_color_diff_old_moved_dimmed: ""
autonomy_gitconfig_color_diff_whitespace: ""
autonomy_gitconfig_color_decorate_branch: ""
autonomy_gitconfig_color_decorate_remote_branch: ""
autonomy_gitconfig_color_decorate_tag: ""
autonomy_gitconfig_color_decorate_stash: ""
autonomy_gitconfig_color_decorate_head: ""
autonomy_gitconfig_color_decorate_grafted: ""

autonomy_gitconfig_core_editor: ""
autonomy_gitconfig_core_excludes_files: ""
autonomy_gitconfig_core_pager: ""
autonomy_gitconfig_core_whitespace: ""

autonomy_gitconfig_init_default_branch: "main"

autonomy_gitconfig_user_use_config_only: "false"
