---
# Realm User Management / Password Requirements
autonomy_realm_identity_management_system: ""
autonomy_realm_min_id_number: 10000
autonomy_realm_max_id_number: 99999

# ==================================================================================================
#
# Samba
#
# ==================================================================================================
# Samba
samba_password_legnth: "{{ autonomy_password_length }}"
samba_domain: no

domain_users: []

# Samba LDAP lookups
samba_user_class: "(objectClass=person)"
samba_group_class: "(objectClass=group)"
samba_search: "(|(userPrincipalName=%uid)(sAMAccountName=%uid)(mail=%uid))"
samba_enabled_users: "(! (userAccountControl:1.2.840.113556.1.4.803:=2))"
samba_member_of: "memberOf:1.2.840.113556.1.4.1941:"

domain_user_vmail:
  username: "vmail"
  spns:
    - spn: "imap"
      host: "{{ autonomy_internal_mail_host }}"
      keytab_file: "/etc/dovecot/dovecot.keytab"
    - spn: "smtp"
      host: "{{ autonomy_internal_mail_host }}"
      keytab_file: "/etc/dovecot/dovecot.keytab"
  account_expire: "--noexpiry"

domain_user_mediawiki:
  username: "mediawiki"
  spns:
    - spn: "HTTP"
      host: "{{ autonomy_internal_www_host }}"
      keytab_file: "/etc/apache2/wiki.{{ autonomy_domain }}.keytab"
  account_expire: "--noexpiry"

domain_user_keycloak:
  username: "keycloak"
  spns:
    - spn: "HTTP"
      host: "{{ autonomy_internal_keycloak_host }}"
      keytab_file: "{{ keycloak_home }}/standalone/configuration/keycloak.keytab"
    - spn: "HTTP"
      host: "{{ autonomy_dmz_keycloak_host }}"
      keytab_file: "{{ keycloak_home }}/standalone/configuration/keycloak.keytab"
  account_expire: "--noexpiry"

domain_user_nextcloud:
  username: "nextcloud"
  spns:
    - spn: "HTTP"
      host: "{{ autonomy_dmz_www_host }}"
  account_expire: "--noexpiry"
