---
# defaults file for users
autonomy_users_packages: []

autonomy_users:
  - "{{ autonomy_user1 }}"
  - "{{ autonomy_user2 }}"
  - "{{ autonomy_user3 }}"

autonomy_user_groups:
  - name: ssl-cert
    system: yes

autonomy_user_group_ansible_managed: "ansiblemanaged"
autonomy_user_managed_min_id: 1000
autonomy_user_managed_max_id: 10000

users_sudoers_options:
  - application: "screen"
    options:
      - entity: "Default"
        value: "env_keep += WINDOW"

# ==================================================================================================
#
# User Dotfiles settings
#
# ==================================================================================================
# .gitconfig
autonomy_user_gitconfig_user_use_config_only: "{{ autonomy_gitconfig_user_use_config_only }}"
autonomy_user_gitconfig_core_editor: "{{ autonomy_gitconfig_core_editor }}"
autonomy_user_gitconfig_core_pager: "{{ autonomy_gitconfig_core_pager }}"
autonomy_user_gitconfig_core_excludes_file: ""
autonomy_user_gitconfig_init_default_branch: "{{ autonomy_gitconfig_init_default_branch }}"
autonomy_user_gitconfig_init_template_dir: "{{ autonomy_gitconfig_init_template_dir }}"

# .gitignore
autonomy_users_gitignore: []

# .gnupg/gpg.conf
autonomy_user_dotfiles_gpg_pinentry_mode: "{{ autonomy_gnupg_pinentry_mode }}"
autonomy_user_dotfiles_gpg_personal_cipher_preferences: "{{ autonomy_gnupg_personal_cipher_preferences }}"
autonomy_user_dotfiles_gpg_personal_digest_preferences: "{{ autonomy_gnupg_personal_digest_preferences }}"
autonomy_user_dotfiles_gpg_personal_compress_preferences: "{{ autonomy_gnupg_personal_compress_preferences }}"
autonomy_user_dotfiles_gpg_default_preference_list: "{{ autonomy_user_dotfiles_gpg_personal_digest_preferences + autonomy_user_dotfiles_gpg_personal_cipher_preferences + autonomy_user_dotfiles_gpg_personal_compress_preferences }}"
autonomy_user_dotfiles_gpg_cert_digest_algo: "{{ autonomy_gnupg_cert_digest_algo }}"
autonomy_user_dotfiles_gpg_s2k_digest_algo: "{{ autonomy_gnupg_s2k_digest_algo }}"
autonomy_user_dotfiles_gpg_s2k_cipher_algo: "{{ autonomy_gnupg_cipher_algo }}"
autonomy_user_dotfiles_gpg_comment: "{{ autonomy_gnupg_comment }}"
autonomy_user_dotfiles_gpg_emit_version: "{{ autonomy_gnupg_emit_version }}"
autonomy_user_dotfiles_gpg_greeting: "{{ autonomy_gnupg_greeting }}"
autonomy_user_dotfiles_gpg_keyid_format: "{{ autonomy_gnupg_keyid_format }}"
autonomy_user_dotfiles_gpg_list_options: "{{ autonomy_gnupg_list_options }}"
autonomy_user_dotfiles_gpg_verify_options: "{{ autonomy_gnupg_verify_options }}"
autonomy_user_dotfiles_gpg_with_fingerprint: "{{ autonomy_gnupg_with_fingerprint }}"
autonomy_user_dotfiles_gpg_require_cross_certification: "{{ autonomy_gnupg_require_cross_certification }}"
autonomy_user_dotfiles_gpg_symkey_cache: "{{ autonomy_gnupg_symkey_cache }}"
autonomy_user_dotfiles_gpg_throw_keyids: "{{ autonomy_gnupg_throw_keyids }}"
autonomy_user_dotfiles_gpg_with_keygrip: "{{ autonomy_gnupg_with_keygrip }}"
autonomy_user_dotfiles_gpg_keyserver_options: "{{ autonomy_gnupg_keyserver_options }}"

# .gnupg/dirmngr.conf
autonomy_user_dotfiles_gpg_keyservers: "{{ autonomy_gnupg_keyservers }}"
autonomy_user_dotfiles_gpg_use_tor: "{{ autonomy_gnupg_use_tor }}"

# .gnupg/gpg-agent.conf
autonomy_user_dotfiles_gpg_pinentry_program: "/usr/bin/pinentry"
autonomy_user_dotfiles_gpg_allow_loopback_pinentry: true
autonomy_user_dotfiles_gpg_allow_emacs_pinentry: false
autonomy_user_dotfiles_gpg_default_cache_ttl: 600
autonomy_user_dotfiles_gpg_default_cache_ttl_ssh: 1800
autonomy_user_dotfiles_gpg_max_cache_ttl: 7200
autonomy_user_dotfiles_gpg_default_max_cache_ttl_ssh: 7200
autonomy_user_dotfiles_gpg_enable_ssh_support: no

# .gnupg/scdaemon.conf
autonomy_user_dotfiles_gpg_pcsc_driver: "/usr/lib/x86_64-linux-gnu/libpcsclite.so.1"
autonomy_user_dotfiles_gpg_disable_ccid: false
autonomy_user_dotfiles_gpg_pcsc_shared: false
autonomy_user_dotfiles_gpg_reader_port: []

# Misc
autonomy_users_dotfiles_users: "{{ autonomy_users }}"
autonomy_users_dotfiles_home: "/home"
autonomy_user_dotfiles_mode: "0700"

# ===================================================================================================
#
# Emacs Settings
#
# ==================================================================================================
autonomy_user_dotfiles_emacsd_repo: ""
autonomy_user_dotfiles_emacsd_repo_remote: "origin"
autonomy_user_dotfiles_emacsd_repo_version: "main"

# ==================================================================================================
#
#
#
# ==================================================================================================
__user_groups:
  - name: ansiblemanaged
    system: yes
  - name: users
    system: yes
  - name: wheel
    system: yes

__users: "{{ autonomy_users }}"

__default_mikrotik_device_user: "admin"

__username_list: []

__samba_domain_groups:
  - groupname: ansiblemanaged

__realm_user_dn_list: []
