---
# defaults file for mail-server
autonomy_dovecot_packages:
  - dovecot-core
  - dovecot-imapd
  - dovecot-lmtpd
  - dovecot-managesieved
  - dovecot-sieve

# ==================================================================================================
#
# Directories
#
# ==================================================================================================
autonomy_dovecot_etc: "/etc/dovecot"
autonomy_dovecot_confd: "{{ autonomy_dovecot_etc }}/conf.d"
autonomy_dovecot_sieve_dir: "{{ autonomy_dovecot_etc }}/sieve"
autonomy_dovecot_sieve_global_dir: "{{ autonomy_dovecot_sieve_dir }}/global"
autonomy_dovecot_sieve_pipe_bin_dir: "/usr/lib/dovecot/sieve"
autonomy_dovecot_virtual_dir: "{{ autonomy_dovecot_etc }}/virtual"
autonomy_vmail_dir: "/var/mail/vmail"
autonomy_dovecot_use_inboxzero_namespace: no
autonomy_dovecot_inboxzero_namespace_name: "inboxzero"
autonomy_dovecot_inboxzero_dir: "{{ autonomy_dovecot_etc }}/{{ autonomy_dovecot_inboxzero_namespace_name }}"

autonomy_dovecot_log_path: syslog
autonomy_dovecot_log_dir: ""
autonomy_dovecot_info_log_path: ""
autonomy_dovecot_debug_log_path: ""

autonomy_dovecot_conf_files:
  - 10-auth.conf
  - 10-director.conf
  - 10-logging.conf
  - 10-mail.conf
  - 10-master.conf
  - 10-ssl.conf
  - 10-tcpwrapper.conf
  - 15-lda.conf
  - 15-mailboxes.conf
  - 20-imap.conf
  - 20-lmtp.conf
  - 20-managesieve.conf
  - 90-acl.conf
  - 90-plugin.conf
  - 90-quota.conf
  - 90-sieve-extprograms.conf
  - 90-sieve.conf
  - auth-checkpassword.conf.ext
  - auth-dict.conf.ext
  - auth-master.conf.ext
  - auth-static.conf.ext
  - auth-vpopmail.conf.ext

# ==================================================================================================
#
# Namespaces
#
# ==================================================================================================
autonomy_dovecot_junk_mail_folder: "Junk"
autonomy_dovecot_infected_mail_folder: "Infected"
autonomy_dovecot_bounce_folder_name: ""
autonomy_dovecot_advertisements_folder_name: ""

autonomy_dovecot_private_namespace_mailboxes:
  - name: "Sent"
    auto: "subscribe"
    special_use: "\\Sent"
  - name: Drafts
    special_use: "\\Drafts"
    auto: "subscribe"
  - name: "{{ autonomy_dovecot_junk_mail_folder }}"
    special_use: "\\Junk"
    auto: "subscribe"
  - name: "Trash"
    special_use: "\\Trash"
    autoexpunge: "30 days"
    auto: "subscribe"
  - name: "Archive"
    special_use: "\\Archive"
    auto: "subscribe"

autonomy_dovecot_bounce_folder:
  name: "{{ autonomy_dovecot_bounce_folder_name }}"
  auto: "subscribe"
  #autoexpunge: "30 days"

autonomy_dovecot_advertisements_folder:
  name: "{{ autonomy_dovecot_advertisements_folder_name }}"
  auto: "subscribe"
  #autoexpunge: "30 days"

autonomy_dovecot_private_namespace:
  name: "private"
  inbox: "yes"
  type: private
  separator: "/"
  prefix:
  #location:
  #hidden: "no"
  list: "yes"
  subscriptions: "yes"
  mailboxes: "{{ autonomy_dovecot_private_namespace_mailboxes }}"

autonomy_dovecot_virtual_namespace:
  name: "virtual"
  prefix: "Virtual/"
  separator: "/"
  hidden: "no"
  list: "yes"
  subscriptions: "no"
  location: "virtual:{{ autonomy_dovecot_virtual_dir }}:INDEX={{ autonomy_vmail_dir }}/%d/%n/virtual"
  mailboxes:
    - name: "All"
      special_use: "\\All"
      comment: All my messages
      auto: create
    - name: "Flagged"
      special_use: "\\Flagged"
      comment: "All my flagged messages"
      auto: "create"
    - name: Important
      comment: "All my important messages"
      auto: "create"
    - name: Recent
      comment: "All my recent messages"
      auto: "create"
    - name: Unread
      comment: "All my unread messages"
      auto: "create"
    - name: Later
      comment: "Reference for later"
      auto: "create"
    - name: Personal
      comment: "Personal messages"
      auto: "create"
    - name: Todo
      comment: "Things to do"
      auto: "create"
    - name: Work
      comment: "Work related messages"
      auto: "create"

autonomy_dovecot_inboxzero_inbox_name: "0-Inbox"
autonomy_dovecot_inboxzero_followup_name: "1-FollowUp"
autonomy_dovecot_inboxzero_hold_name: "2-Hold"

autonomy_dovecot_inboxzero_namespace:
  name: "{{ autonomy_dovecot_inboxzero_namespace_name }}"
  prefix: "{{ autonomy_dovecot_inboxzero_inbox_name }}/"
  separator: "/"
  hidden: "no"
  list: "yes"
  subscriptions: "no"
  location: "virtual:{{ autonomy_dovecot_inboxzero_dir }}:INDEX={{ autonomy_vmail_dir }}/%d/%n/{{ autonomy_dovecot_inboxzero_namespace_name }}"
  mailboxes:
    - name: "{{ autonomy_dovecot_inboxzero_inbox_name }}"
      comment: "All my unread messages."
      auto: "create"
    - name: "{{ autonomy_dovecot_inboxzero_followup_name }}"
      comment: "Messages I need to follow up on."
      auto: "create"
    - name: "{{ autonomy_dovecot_inboxzero_hold_name }}"
      comment: "Reference messages for upcoming tasks and events."
      auto: "create"

autonomy_dovecot_shared_namespace:
  name: "shared"
  type: "shared"
  separator: "/"
  prefix: "shared/%%u/"
  #location: maildir:%%h/Maildir:INDEX=~/Maildir/shared/%%u
  #subscriptions: "no"
  #list: children

autonomy_dovecot_public_namespace:
  names: "public"
  type: "public"
  separator: "/"
  prefix: "public/%%u/"
  #location: maildir:%%h/Maildir:INDEX=~/Maildir/shared/%%u
  #subscriptions: "no"
  #list: children

autonomy_dovecot_namespaces:
  - "{{ autonomy_dovecot_private_namespace }}"
  - "{{ autonomy_dovecot_virtual_namespace }}"

# ==================================================================================================
#
# Sieve Settings
#
# ==================================================================================================
autonomy_dovecot_sieve: "file:~/.sieve;active=~/.dovecot.sieve"
autonomy_dovecot_sieve_before:
  - "{{ autonomy_dovecot_etc }}/sieve/before/"

autonomy_dovecot_sieve_after:
  - "{{ autonomy_dovecot_etc }}/sieve/after/"
autonomy_dovecot_sieve_global: "{{ autonomy_dovecot_sieve_global_dir }}/"
autonomy_dovecot_sieve_global_extensions: "+vnd.dovecot.pipe +vnd.dovecot.execute +vnd.dovecot.filter"

autonomy_dovecot_sieve_files:
  - name: "spam"
    priority: "10"
    type: "before"
  - name: "mailbomb"
    priority: "20"
    type: "before"
  - name: "duplicate"
    priority: "30"
    type: "before"
  - name: "flags"
    priority: "40"
    type: "before"
  - name: "flags"
    priority: "40"
    type: "global"
  - name: "mailinglists"
    priority: "90"
    type: "global"
  - name: "recipient-detail-sort"
    priority: "98"
    type: "global"
  - name: "sender-domain-sort"
    priority: "97"
    type: "global"
  - name: "sender-name-sort"
    priority: "97"
    type: "global"
  - name: "sort"
    priority: "99"
    type: "global"
  - name: "sort"
    priority: "99"
    type: "global"
    archive: yes

autonomy_dovecot_sieve_plugins: "sieve_imapsieve sieve_extprograms"
# ==================================================================================================
#
# Virtual Mailbox
#
# ==================================================================================================
autonomy_dovecot_virtual_mailboxes:
  - name: "All"
    folders:
      - "*"
      - "Trash"
      - "Trash/*"
      - "Sent"
      - "Sent/*"
      - "-Junk"
      - "-Junk/*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "all"
  - name: "Flagged"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "flagged"
  - name: "Important"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "OR KEYWORD $label1 KEYWORD $Labelimportant"
  - name: "Work"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "OR KEYWORD $label2 KEYWORD $Labelwork"
  - name: "Personal"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "OR KEYWORD $label3 KEYWORD $Labelpersonal"
  - name: "Todo"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "OR KEYWORD $label4 KEYWORD $Labeltodo"
  - name: "Later"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "OR KEYWORD $Labellater KEYWORD $label5"
  - name: "Recent"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "all younger 172800"
  - name: "Unread"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "unseen"

autonomy_dovecot_inboxzero_mailboxes:
  - name: "0-Inbox"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "unseen"
  - name: "1-FollowUp"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "OR (OR (OR KEYWORD $label1 KEYWORD $Labelimportant) (OR KEYWORD $label4 KEYWORD $Labeltodo)) flagged"
  - name: "2-Hold"
    folders:
      - "*"
      - "-Inbox/Trash"
      - "-Inbox/Trash/*"
      - "-Inbox/Junk"
      - "-Inbox/Junk/*"
      - "-Inbox/Sent"
      - "-Inbox/Sent/*"
    search:
      - "OR KEYWORD $Labellater KEYWORD $label5"

# ==================================================================================================
#
# Misc Settings
#
# ==================================================================================================
autonomy_dovecot_migration_users:
  - account: "bob@example.com"
    password: "password"


autonomy_dovecot_password_databases: []

autonomy_dovecot_mail_plugins: "acl virtual"
autonomy_dovecot_imap_mail_plugins: "imap_sieve"
autonomy_dovecot_lmtp_mail_plugins: "sieve"
autonomy_dovecot_lda_mail_plugins: "sieve"

autonomy_dovecot_mail_protocols:
  - name: "!indexer-worker"

autonomy_dovecot_imap_protocols:
  - name: imap
    mail_plugins: "$mail_plugins imap_sieve"

autonomy_dovecot_imapsieve_mailboxes:
  - name: "Junk"
    causes: "COPY"
    timing: "before"
    type: "spam"
  - name: "*"
    from: "Junk"
    causes: "COPY"
    timing: "before"
    type: "ham"

autonomy_dovecot_mail_debug: "no"

# ==================================================================================================
#
# Dovecot Authorization Configuration
#
# ==================================================================================================
autonomy_dovecot_auth_mechanisms:
  - plain
  - login

autonomy_dovecot_auth_conf_system:
  name: "system"
  passdb:
    - driver: "pam"
  userdb:
    - driver: "static"
      args: "allow_all_users=yes uid={{ user_vmail_id_number }} gid={{ user_vmail_id_number }} home={{ autonomy_vmail_dir }}/%d/%n"

autonomy_dovecot_auth_conf_sql:
  name: "sql"
  passdb:
    - driver: "sql"
      args: "{{ autonomy_dovecot_etc }}/dovecot-sql.conf.ext"
  userdb:
    - driver: "sql"
      args: "{{ autonomy_dovecot_etc }}/dovecot-sql.conf.ext"

autonomy_dovecot_auth_conf_ldap:
  name: "ldap"
  passdb:
    - driver: "ldap"
      args: "{{ autonomy_dovecot_etc }}/dovecot-ldap.conf.ext"
  userdb:
    - driver: "ldap"
      args: "{{ autonomy_dovecot_etc }}/dovecot-ldap.conf.ext"

autonomy_dovecot_auth_conf_oauth2:
  name: "oauth2"
  passdb:
    - driver: "oauth2"
      mechanisms: "xoauth2 oauthbearer"
      args: "{{ autonomy_dovecot_etc }}/dovecot-oauth2.conf.ext"

autonomy_dovecot_auth_conf:
  - "{{ autonomy_dovecot_auth_conf_system }}"

autonomy_dovecot_auth_deny:
  name: "deny"
  passdb:
    - driver: passwd-file
      deny: yes
      args: "{{ autonomy_dovecot_etc }}/deny-users"

autonomy_dovecot_password_file: "{{ autonomy_dovecot_etc }}/passwd.db"

autonomy_dovecot_auth_conf_passwdfile:
  name: "passwdfile"
  passdb:
    - driver: "passwd-file"
      args: "username_format=%u scheme=ssha512 {{ autonomy_dovecot_password_file }}"
      deny: "no"
      master: "no"
      pass: "no"
      skip: "never"
      result_failure: "continue"
      result_internalfail: "continue"
      result_success: "return-ok"
  userdb:
    - driver: passwd-file
      args: "username_format=%u {{ autonomy_dovecot_etc }}/users"

autonomy_dovecot_sieve_mime_flags:
  - mime_type: "application/ics"
    flags: "invites"
  - mime_type: "text/x-vcard"
    flags: "contact"

autonomy_dovecot_auth_use_winbind: ""
autonomy_dovecot_auth_winbind_helper_path: ""

# The following variables are not modified from the application defaults.

autonomy_dovecot_default_vsz_limit: "{{ __autonomy_dovecot_default_vsz_limit }}"
autonomy_dovecot_process_min_avail: "{{ __autonomy_dovecot_process_min_avail }}"
autonomy_dovecot_log_debug: ""

# ==================================================================================================
#
# Dovecot Defaults
#
# ==================================================================================================
__autonomy_dovecot_sieve_global: ""
__autonomy_dovecot_default_vsz_limit: "256M"
__autonomy_dovecot_process_min_avail: 0
