---
autonomy_ownca_packages:
  - python3-cryptography
  - python3-openssl
  - rng-tools
  - ca-certificates

autonomy_ownca_host_packages: "{{ autonomy_ownca_packages }}"




autonomy_ownca_intermediate_ca: "{{ autonomy_org_unit_name | lower }}"

autonomy_ownca_users_dir: "{{ autonomy_ownca_directory }}/users"
#autonomy_ownca_user_pki_dir: "{{ autonomy_user_pki_dir }}"
autonomy_ownca_users_cert_dir: "{{ autonomy_ownca_users_dir }}/certs"
autonomy_ownca_users_csr_dir: "{{ autonomy_ownca_users_dir }}/csr"
autonomy_ownca_users_private_dir: "{{ autonomy_ownca_users_dir }}/private"
autonomy_ownca_users_pkcs12_dir: "{{ autonomy_ownca_users_dir }}/pkcs12"

autonomy_ownca_home_dir: "/home"

autonomy_ownca_etc_privatekey_path: "{{ autonomy_ownca_etc }}/private/{{ autonomy_fqdn }}.key"
autonomy_ownca_host_privatekey_path: "{{ autonomy_ownca_hosts_directory }}/private/{{ autonomy_fqdn }}.key"

autonomy_ownca_host_certs_directories:
  - name: private
    mode: "{{ __ownca_privatekey_dir_mode }}"
    group: "{{ __ownca_privatekey_dir_group }}"
  - name: csr
    mode: "0700"
  - name: pkcs12
    mode: "0700"
  - name: certs
    mode: "0755"
  - name: crls
    mode: "0755"
  - name: dhparams
    mode: "0755"

autonomy_ownca_user_dirs:
  - name: private
    mode: "0700"
  - name: csr
    mode: "0755"
  - name: "certs"
    mode: "0755"
  - name: "pkcs12"
    mode: "0755"
  - name: "ssh"
    mode: "0755"

autonomy_ownca_user_directories:
  - name: "csr"
    mode: "0755"
  - name: "certs"
    mode: "0755"

autonomy_ownca_privatekey_group: "root"
autonomy_ownca_privatekey_mode: "0600"

autonomy_ownca_generate_locally: no

autonomy_ownca_host_certs_pkcs12_password: "password"
autonomy_ownca_host_certs_subject_alt_name:
  - "DNS:{{ autonomy_fqdn }}"
  - "IP:{{ ansible_host }}"

autonomy_ownca_host_certs_extended_key_usage:
  - serverAuth
  - clientAuth

autonomy_ownca_host_certs_key_usage:
  - digitalSignature
  - keyEncipherment

autonomy_ownca_objectguid: ""

autonomy_ownca_revoked_certificates: []

autonomy_ownca_crl_distribution_points:
  - "{{ autonomy_org_name }}-root-ca"

# Passwords
autonomy_ownca_password_length: "{{ autonomy_password_length }}"
autonomy_ownca_user_password_length: "{{ autonomy_ownca_password_length }}"

# ==================================================================================================
#
# The following variables are modified based on system information (host groups, OS Family, etc).
#
# These variables are not designed for user configuration.
#
# ==================================================================================================
__ownca_privatekey_dir_mode: "0700"
__ownca_privatekey_dir_group: "root"

__ownca_force_regeneration: false

# Root CA Regeneration
__ownca_rootca_privatekey_force_regeneration: "{{ __ownca_force_regeneration }}"
__ownca_rootca_csr_force_regeneration: "{{ __ownca_rootca_privatekey_force_regeneration }}"
__ownca_rootca_cert_force_regeneration: "{{ __ownca_rootca_csr_force_regeneration }}"

# Intermediate CA Certificate Regeneration
__ownca_intermediateca_privatekey_force_regeneration: "{{ __ownca_force_regeneration }}"
__ownca_intermediateca_csr_force_regeneration: >-
  {% if __ownca_intermediateca_privatekey_force_regeneration or
        __ownca_rootca_cert_force_regeneration %}
  true
  {% else %}
  false
  {% endif %}
__ownca_intermediateca_cert_force_regeneration: >-
  {{ __ownca_intermediateca_csr_force_regeneration }}

# Issuing CA Certificate Regeneration
__ownca_issuingca_privatekey_force_regeneration: "{{ __ownca_force_regeneration }}"
__ownca_issuingca_csr_force_regeneration: >-
  {% if __ownca_issuingca_privatekey_force_regeneration or
        __ownca_intermediateca_cert_force_regeneration %}
  true
  {% else %}
  false
  {% endif %}
__ownca_issuingca_cert_force_regeneration: >-
  {{ __ownca_issuingca_csr_force_regeneration }}

# Host Certificate Regeneration
__host_privatekey_force_regeneration: "{{ __ownca_force_regeneration }}"
__host_csr_force_regeneration: >-
  {% if __host_privatekey_force_regeneration or
        __ownca_issuingca_cert_force_regeneration %}
  true
  {% else %}
  false
  {% endif %}
__host_cert_force_regeneration: "{{ __host_csr_force_regeneration }}"
__host_dhparams_force_regeneration: "{{ __ownca_force_regeneration }}"

# User Certificate Regeneration
__user_privatekey_force_regeneration: "{{ __ownca_force_regeneration }}"
__user_csr_force_regeneration: >-
  {% if __user_privatekey_force_regeneration or
        __ownca_issuingca_cert_force_regeneration %}
  true
  {% else %}
  false
  {% endif %}
__user_cert_force_regeneration: "{{ __user_csr_force_regeneration }}"

__ownca_certificate_authorities_id:
  - "ca"
  - "component-ca"
  - "identity-ca"


